### ISSUE TITLE
[OneNote] Importer does not back off, leading to rate limiting

### ISSUE THREAD

**Issue by voltagex** [obsidianmd/obsidian-importer#120]
I have a whole lot of files that have 

`{"error":{"code":"20166","message":"The app has issued too many requests on behalf of this user in a short time period.","innerError":{"date":"2023-09-25T08:41:06","request-id":"e4c11a53-8e0a-4891-b070-b74db5279b13","client-request-id":"e4c11a53-8e0a-4891-b070-b74db5279b13"}}}`

instead of content.

**Comment by ashemedai** [comment]
This link has some details on the limits and how to build better API calls to drain the rate limit less quickly: https://learn.microsoft.com/en-us/graph/throttling-limits#onenote-service-limits

**Comment by chairman2s** [comment]
Same problem here

**Comment by hakenr** [comment]
same here

**Comment by hakenr** [comment]
The limits are pretty restrictive 😭 - 120 req/min && 400 req/hr
https://learn.microsoft.com/en-us/graph/throttling-limits#onenote-service-limits

**Comment by ashemedai** [comment]
@hakenr They're restrictive if you're just throwing sequential requests at the API. Within that same link, that I posted 3 weeks ago as well, they also document how to restructure your query requests to not need multiple calls to get data.

**Comment by tgrosinger** [comment]
This should be resolved in the latest release - [1.6.1](https://github.com/obsidianmd/obsidian-importer/releases/tag/1.6.1)

**Comment by kquinsland** [comment]
I am still getting 429's which manifest in other errors.  I'll open a new issue
