### ISSUE TITLE
Apple Notes: Drawings not imported

### ISSUE THREAD

**Issue by kepano** [obsidianmd/obsidian-importer#134]
Drawings in imported Apple Notes show the following error

`**(error reading attachment)**`

We should try to import/convert the drawing, or display a more useful error

**Comment by kepano** [comment]
@mirnovov what is the storage format for drawings?

**Comment by mirnovov** [comment]
Drawings are stored as a format containing their lines etc, similar to SVG. However, a fallback image is generated, which this importer uses. I believe I've found a bug where the path for this image is resolved incorrectly which will probably fix this issue.

btw @kepano what macOS and iOS versions are you on? and were your drawings and scans created on those versions, or earlier?

**Comment by kepano** [comment]
In my test I used iOS 17.0.3 to create the drawing, then synced it to my Mac running macOS 13.0.1 before importing.

**Comment by mirnovov** [comment]
Thanks. In that case, I think it will possibly be fixed by this PR, since the changes to the drawing location are made in macOS 14/iOS 17.

**Comment by rubenIGM** [comment]
Hi guys, unfortunately this problem persists, iOS 16.7.5 and Ventura 13.4. the drawings fail to import.

**Comment by andrewcrook** [comment]
I have also written some notes about this  [here ](https://github.com/obsidianmd/obsidian-importer/issues/203#issuecomment-1936984926)

I think the issue is to do with old notes like #137 . If I clean out notes and create new notes it works fine.
It seems to me to have something to do with the ZIDIDENTIFIER in the notes db, unformantly I no longer have any old notes to look at in the db.

**Comment by mbewley** [comment]
Have been using apple notes on the iPad over the years with apple pencil/handwriting. I get these errors on every note with handwriting:

Failed: "<name of note>" because Cannot read properties of undefined (reading 'ZIDENTIFIER')

Newer notes seem to get imported, but with " **(error reading attachment)**" instead of the chunk of handwriting.
Older notes are raised as a "failed" import note with the ZIDENTIFIER error above, and the entire note is empty, even if it was a mix of handwriting and plain text.

Anything I can do to help troubleshoot?

**Comment by andrewcrook** [comment]
I am thinking if there are two separate issues here?

ZIDENTIFIER with old notes 

 and the other, I wonder it has something to do with the fact that there are currently two iCloud modes normal and advanced data protection?

![Screenshot 2024-02-25 at 17 50 22](https://github.com/obsidianmd/obsidian-importer/assets/803618/ebd11843-d7c4-42ff-a42b-cb63f95a79c8)

**Comment by tommasodiotalevi** [comment]
I also have a similar issue: I tried to import my Apple notes, and I receive the following failure:
```
...
Failed: "DATASET NAME RULE" because Cannot read properties of undefined (reading 'ZIDENTIFIER')
...
```
In these notes, I have text alternated to text drawings made with the Apple pencil.

**Comment by tgrosinger** [comment]
Closing this issue in favor of #218 which tracks what seems to be the current problem people are encountering.
